angular.module('meanApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('views/about.html',
    "<p>This is the about view.</p>"
  );


  $templateCache.put('views/atencion.html',
    "<p>This is the atencion view.</p>"
  );


  $templateCache.put('views/dashboard.html',
    "<div ng-controller=\"DashboardCtrl\"> <div class=\"col-md-12 text-center\"> <h3 class=\"text-center\"><label class=\"label label-default\">Mostrando {{distrib.name}}</label></h3> <h4 class=\"text-center\"><label class=\"label label-default\">{{period.alias}}</label></h4> <button class=\"vert-offset-top-1 btn btn-default\" ng-repeat=\"distrib in distribuidoras\" ng-click=\"changeDistrib($index)\">{{distrib.alias|uppercase}}</button> </div> <div class=\"col-md-12 text-center\"> <button class=\"btn btn-default\" ng-repeat=\"period in periodos\" ng-click=\"changePeriod($index)\">{{period.alias}}</button> </div> <div class=\"vert-offset-top-1 col-md-6\"> <h3 class=\"text-center\">{{period.alias}}: Estado de ficheros</h3> <canvas id=\"base\" class=\"chart-base\" chart-type=\"stateChartType\" chart-colours=\"stateChartColours\" chart-data=\"stateChartData\" chart-labels=\"stateChartLabels\" chart-legend=\"true\"> </canvas> </div> <div class=\"vert-offset-top-1 col-md-6\"> <h3 class=\"text-center\">{{period.alias}}: Evolución de estados</h3> <canvas id=\"line\" class=\"chart chart-line\" chart-data=\"evolveStateChartData\" chart-colours=\"evolveStateChartColours\" chart-labels=\"evolveStateChartLabels\" chart-legend=\"true\" chart-series=\"evolveStateChartSeries\" chart-click=\"onClick\"> </canvas> </div> <div class=\"vert-offset-top-4 col-md-12 vert-offset-bottom-6\"> <div class=\"col-md-4\"> <div class=\"panel panel-default\"> <div class=\"panel-heading panel-title text-center\">Ficheros que requieren atención por distribuidora</div> <div class=\"panel-body\"> <div class=\"list-group\"> <a href=\"#/atencion/distrib/{{distrib.codigo}}\" class=\"list-group-item\" ng-repeat=\"distrib in distribArray\">{{distrib.nombre}}<span class=\"badge\">{{distrib.reqAtencion}}</span></a> </div> </div> </div> </div> <div class=\"col-md-4\"> <div class=\"panel panel-default\"> <div class=\"panel-heading panel-title text-center\">Ficheros que requieren atención por tipo</div> <div class=\"panel-body\"> <div class=\"list-group\"> <!--<a href=\"#/atencion/tipo/{{typeName}}\" class=\"list-group-item\" ng-repeat=\"(typeName,counter) in typeArrayPanel\">{{typeName}}<span class=\"badge\">{{counter}}</span></a>\n" +
    "            --> </div> </div> </div> </div> <div class=\"col-md-4\"> <div class=\"panel panel-default\"> <div class=\"panel-heading panel-title text-center\">Ficheros que requieren atención por lo que sea</div> <div class=\"panel-body text-center\">asdasd asdsda</div> </div> </div> </div> </div>"
  );


  $templateCache.put('views/entrada/detalle.html',
    "<p>This is the detalle view.</p>"
  );


  $templateCache.put('views/entrada/entrada.html',
    "<div ng-controller=\"EntradaCtrl\"> <div class=\"text-center\"> <h3><label class=\"label label-default\">Ficheros de Entrada: {{distrib.name}}</label></h3> </div> <div class=\"col-md-12 text-center vert-offset-top-1\"> <div class=\"btn-group\"> <button class=\"btn btn-default\" ng-class=\"{'btn-primary': d === distrib}\" ng-repeat=\"d in distribuidoras\" ng-click=\"changeDistrib($index)\">{{d.alias|uppercase}}</button> </div> </div> <div class=\"col-md-12 text-center\"> <div class=\"btn-group\"> <button class=\"btn btn-default\" ng-class=\"{'btn-primary': p === period}\" ng-repeat=\"p in periodos\" ng-click=\"changePeriod($index)\">{{p.alias}}</button> </div> </div> <div class=\"col-md-12 text-center\"> <div class=\"btn-group\"> <label class=\"btn btn-default disabled\">Omitir los siguientes tipos</label> <label class=\"btn btn-default\" ng-repeat=\"(state,value) in omitTypes\" ng-change=\"refreshTable()\" ng-model=\"omitTypes[state]\" uib-btn-checkbox>{{state}}</label> </div> </div> <div class=\"col-md-12 vert-offset-top-2 vert-offset-bottom-6\"> <div class=\"col-md-7\" id=\"tableDiv\"> <div class=\"panel panel-primary\"> <div class=\"panel-heading\"><h3 class=\"panel-title\">Registro de entrada</h3></div> <div class=\"panel-body\"> <table ng-table=\"tableParams\" class=\"table\" show-filter=\"true\"> <tr ng-click=\"selectFile(file, $index)\" ng-class=\"{selected: $index === idSelectedFile}\" class=\"animate\" ng-repeat=\"file in $data\"> <td title=\"'Nombre'\" filter=\"{'filename': 'text'}\" sortable> <a ng-href=\"http://{{serverConfig.host}}:{{serverConfig.port}}/api/file/{{distrib.alias}}/{{distrib.code}}/inputFs/{{file.filename}}\">{{file.filename}}</a> </td> <!--\n" +
    "              <td title=\"'Tipo'\" filter=\"{ 'type': 'text'}\" sortable=\"'type'\">\n" +
    "                  {{file.type | uppercase}}\n" +
    "              </td>\n" +
    "              <td title=\"'Emisor'\" filter=\"{ 'sourceParticipant': 'text'}\" sortable=\"'sourceParticipant'\">\n" +
    "                  {{file.sourceParticipant | uppercase}}\n" +
    "              </td>\n" +
    "              --> <td title=\"'Fecha'\" filter=\"{ uploadDate: 'text'}\" sortable> {{file.uploadDate | date:\"dd/MM/yyyy 'a las' HH:mm\"}} </td> </tr> </table> </div> </div> </div> <div ng-show=\"idSelectedFile >= 0\" class=\"col-md-5\"> <div class=\"panel panel-primary\"> <div class=\"panel-heading\"><h3 class=\"panel-title\">Linea de tiempo del fichero seleccionado</h3></div> <div class=\"panel-body timeline\"> <dl> <dt>Abril 2015</dt> <dd class=\"pos-right clearfix\"> <div class=\"circ\"></div> <div class=\"time\">14 de Abril</div> <div class=\"events\"> <div class=\"events-body\"> <h4 class=\"events-heading\">Estado X</h4> <p><small class=\"text-muted\"><i class=\"glyphicon glyphicon-time\"></i> hace 11 horas</small></p> <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua.</p> </div> </div> </dd> <dd class=\"pos-left clearfix\"> <div class=\"circ\"></div> <div class=\"time\">10 de Abril</div> <div class=\"events\"> <div class=\"events-body\"> <h4 class=\"events-heading\">Cambia a estado Y</h4> <p><small class=\"text-muted\"><i class=\"glyphicon glyphicon-time\"></i> hace 4 días</small></p> <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua.</p> </div> </div> </dd> <dt>Marzo 2015</dt> <dd class=\"pos-right clearfix\"> <div class=\"circ\"></div> <div class=\"time\">15 de Marzo</div> <div class=\"events\"> <div class=\"events-body\"> <h4 class=\"events-heading\">Flat UI</h4> <p><small class=\"text-muted\"><i class=\"glyphicon glyphicon-time\"></i> hace X días</small></p> <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua.</p> </div> </div> </dd> <dd class=\"pos-left clearfix\"> <div class=\"circ\"></div> <div class=\"time\">8 de Marzo</div> <div class=\"events\"> <div class=\"events-body\"> <h4 class=\"events-heading\">UI design</h4> <p><small class=\"text-muted\"><i class=\"glyphicon glyphicon-time\"></i> hace XX días</small></p> <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua.</p> </div> </div> </dd> </dl> </div> </div> </div> </div> </div>"
  );


  $templateCache.put('views/login.html',
    "<div ng-controller=\"LoginCtrl\"> <div class=\"vert-offset-top-3\"> <div class=\"col-md-12 text-center vert-offset-bottom-2\"> <h3>Concentrador Secundario de UDESA</h3> </div> <div class=\"col-md-offset-4 col-md-4 col-md-offset-4 vert-offset-bottom-7\"> <form name=\"loginForm\"> <div class=\"form-group\"> <label for=\"username\">Nombre de usuario</label> <input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\" placeholder=\"Nombre de usuario\" ng-model=\"user.username\" required> <div class=\"alert alert-danger\" ng-show=\"loginForm.username.$dirty && loginForm.username.$error.required\"><label>¡Campo obligatorio!</label></div> </div> <div class=\"form-group\"> <label for=\"password\">Contraseña</label> <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" placeholder=\"Contraseña\" ng-model=\"user.password\" required> <div class=\"alert alert-danger\" ng-show=\"loginForm.password.$dirty && loginForm.password.$error.required\"><label>¡Campo obligatorio!</label></div> </div> <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\" ng-show=\"!loginForm.$valid\" disabled>Acceder</button> <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\" ng-show=\"loginForm.$valid\" ng-click=\"login(user)\">Acceder</button> </form> </div> </div> </div>"
  );


  $templateCache.put('views/revficheros.html',
    "<div class=\"row marketing\" ng-controller=\"RevficherosCtrl\"> <div class=\"text-center\"> Selecciona una fecha: <input type=\"daterange\" class=\"btn btn-default dropdown-toggle\" ng-model=\"datepicker\" ranges=\"ranges\" ng-change=\"refreshFileTable()\" format=\"DD MMM YYYY\" separator=\"-\"> <h3><label class=\"label label-default\">Visualizando desde el {{datepicker.startDate|date:\"dd/MM/yyyy\"}} hasta el {{datepicker.endDate|date:\"dd/MM/yyyy\"}}</label></h3> </div> <table ng-table=\"tableParams\" class=\"table\" show-filter=\"true\"> <tr class=\"animate\" ng-repeat=\"file in $data\"> <td title=\"'Nombre'\" filter=\"{ fileName: 'text'}\" sortable> {{file.fileName}} </td> <td title=\"'Tipo'\" filter=\"{ fileType: 'text'}\" sortable> {{file.fileType}} </td> <td title=\"'Fecha de creacion'\" filter=\"{ uploadDate: 'text'}\" sortable> {{file.uploadDate | date:\"dd/MM/yyyy 'a las' hh:mm a\"}} </td> </tr> </table> </div>"
  );


  $templateCache.put('views/salida/detalle.html',
    "<p>This is the detalle view.</p>"
  );


  $templateCache.put('views/salida/salida.html',
    "<div ng-controller=\"SalidaCtrl\"> <div class=\"text-center\"> <h3><label class=\"label label-default\">Ficheros de Salida: {{distrib.name}}</label></h3> </div> <div class=\"col-md-12 text-center vert-offset-top-1\"> <div class=\"btn-group\"> <button class=\"btn btn-default\" ng-class=\"{'btn-primary': d === distrib}\" ng-repeat=\"d in distribuidoras\" ng-click=\"changeDistrib($index)\">{{d.alias|uppercase}}</button> </div> </div> <div class=\"col-md-12 text-center\"> <div class=\"btn-group\"> <button class=\"btn btn-default\" ng-class=\"{'btn-primary': p === period}\" ng-repeat=\"p in periodos\" ng-click=\"changePeriod($index)\">{{p.alias}}</button> </div> </div> <div class=\"col-md-12 text-center\"> <div class=\"btn-group\"> <label class=\"btn btn-default disabled\">Omitir los siguientes estados</label> <label class=\"btn btn-default\" ng-repeat=\"(state,value) in omitStates\" ng-change=\"refreshTable()\" ng-model=\"omitStates[state]\" uib-btn-checkbox>{{state}}</label> </div> </div> <div class=\"col-md-12 vert-offset-top-1 vert-offset-bottom-6\"> <table ng-table=\"tableParams\" class=\"table\" show-filter=\"true\"> <tr ng-class=\"{'green': file.state === 'NO_REQUIERE_ENVIO' ||\n" +
    "                              file.state === 'FICHERO_ENVIADO_OK' ||\n" +
    "                              file.state === 'REE_CONFIRMADO_OK',\n" +
    "                    'red': file.state === 'REE_CONFIRMADO_BAD2' ||\n" +
    "                              file.state === 'REE_CONFIRMADO_BAD' ||\n" +
    "                              file.state === 'FICHERO_ENVIADO_ERROR',\n" +
    "                    'yellow': file.state === 'REE_PDTE_CONFIRMACION'\n" +
    "                    }\" class=\"animate\" ng-repeat=\"file in $data\"> <td title=\"'Nombre'\" filter=\"{'filename': 'text'}\" sortable> <a ng-href=\"http://{{serverConfig.host}}:{{serverConfig.port}}/api/file/{{distrib.alias}}/outputFs/{{file.filename}}\">{{file.filename}}</a> </td> <td title=\"'Tipo'\" filter=\"{ 'type': 'text'}\" sortable> {{file.type}} </td> <td title=\"'Estado'\" filter=\"{'state': 'text'}\" sortable> <span ng-if=\"file.state !== 'REE_CONFIRMADO_BAD2'\">{{file.state}}</span> <a class=\"\" ng-if=\"file.state === 'REE_CONFIRMADO_BAD2'\" ng-href=\"http://{{serverConfig.host}}:{{serverConfig.port}}/api/file/{{distrib.alias}}/{{distrib.code}}/inputFs/{{file.filename}}.bad2\">{{file.state}}</a> </td> <td title=\"'Envio'\" filter=\"{'sendResult': 'text'}\" sortable> {{file.sendResult}} </td> <td title=\"'Generado por'\" filter=\"{'inputFilename':'text'}\" sortable> <a ng-href=\"http://{{serverConfig.host}}:{{serverConfig.port}}/api/file/{{distrib.alias}}/{{distrib.code}}/inputFs/{{file.inputFilename}}\">{{file.inputFilename}}</a> </td> <td title=\"'Fecha de subida'\" filter=\"{ uploadDate: 'text'}\" sortable> {{file.uploadDate | date:\"dd/MM/yyyy 'a las' HH:mm\"}} </td> </tr> </table> </div> </div>"
  );

}]);
